use_frameworks!

platform :ios, '12.0'

target 'IPFSImageClient_Example' do
  pod 'IPFSImageClient', :path => '../'

  target 'IPFSImageClient_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
